# Cette tache permet d’installer PHP et ses dépendances nécessaires pour le fonctionnement d’Apache.
- name: Install PHP and dependencies
  apt:
    name:
      - php
      - libapache2-mod-php
      - php-mysql
      - php-cli
      - php-curl
      - php-intl
      - php-gd
      - php-mbstring
      - php-xml
    state: latest
  changed_when: true
  notify: [ "apache restart" ]